# Dictionary to store all the majors
school_majors = {
    "sse": [
        "engineering management undergraduate major",
        "industrial and systems engineering undergraduate major",
        "software engineering undergraduate major",
    ],
    "sob": [
        "business & technology undergraduate major",
        "quantitative finance undergraduate major",
        "finance undergraduate major",
        "business undecided",
        "accounting and analytics undergraduate major",
        "information systems undergraduate major",
        "management undergraduate major",
        "marketing innovation and analytics undergraduate major",
        "economics undergraduate major",
    ],
    "ses": [
        "computer engineering undergraduate major",
        "biology undergraduate major",
        "chemical engineering undergraduate major",
        "mechanical engineering undergraduate major",
        "computer science undergraduate major",
        "biomedical engineering undergraduate major",
        "civil engineering undergraduate major",
        "mathematics undergraduate major",
        "engineering management undergraduate major",
        "electrical engineering undergraduate major",
        "chemistry undergraduate major",
        "cybersecurity undergraduate major",
        "engineering undecided",
        "physics undergraduate major",
        "chemical biology undergraduate major",
        "environmental engineering undergraduate major",
        "mechanical engineering masters program",
        "engineering undergraduate major",
        "science undecided",
        "industrial and systems engineering undergraduate major",
        "machine learning masters program",
        "data science masters program",
        "computer engineering masters program",
        "chemistry masters program",
        "cybersecurity masters program",
        "biomedical engineering masters program",
    ],
    "hass": [
        "philosophy undergraduate major",
        "social science undergraduate major",
        "visual arts and technology undergraduate major",
        "music and technology undergraduate major",
        "science communication undergraduate major",
        "science, technology and society undergraduate major",
        "quantitative social science undergraduate major",
        "literature undergraduate major",
        "humanities and arts undecided",
        "business administration masters program",
    ],
}
